import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyGremio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao <br></br>
          <a href="https://localhost:3000">MyGrêmio!!</a>
        </h1>

        <p className={styles.description}>de gremistas para gremistas!</p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Notícias &rarr;</h2>
            <p>Fiquei pode dentro do que acontece com seu time do coração.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Escalações &rarr;</h2>
            <p>
              Quer saber quem vai jogar ou quem jogou os ultimos jogos? Chega
              ai!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Curiosidades &rarr;</h2>
            <p>
              Gostaria de conhecer melhor o nosso Grêmio? Aqui você consegue.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Sobre nós &rarr;</h2>
            <p>Clique aqui para conhecer um pouco mais do nosso trabalho ♥.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/jrsbaum"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by jrsbaum & natheus
        </a>
      </footer>
    </div>
  );
}
